### ISSUE TITLE
Could this be expanded to benchmark against WHO standards also?

### ISSUE THREAD

**Issue by Lingtax** [ropenscilabs/mchtoolbox#63]
Given much of the underlying code would be the same, could WHO standards also be included either as separate functions or as an argument in a broader growth function?

WHO standards are preferred for some ages: https://www.cdc.gov/growthcharts/who_charts.htm 
The standard options for the WHO standards are some pretty chunky scripts: http://www.who.int/childgrowth/software/en/ 

WHO Standards are here: http://www.who.int/childgrowth/standards/en/

**Comment by smouksassi** [comment]
https://github.com/HBGDki/growthstandards 
Refer to this package and others under HBGDki for a lot of things related to healthy growth. It has a lot of functions that help
