### ISSUE TITLE
Shiny app crashes when uploading data

### ISSUE THREAD

**Issue by kylehamilton** [ropenscilabs/mchtoolbox#66]
When I upload the example data into the Shiny app I get the follow error printed in console and in the shiny app.

`> launch_mchtoolbox()

Listening on http://127.0.0.1:3317
Warning: Error in scale_colour_viridis_d: could not find function "scale_colour_viridis_d"
  164: renderPlot [C:\Users\Kyle Hamilton\Documents\R\win-library\3.5\mchtoolbox\shiny/server.R#53]
  162: func
  122: drawPlot
  108: <reactive:plotObj>
   92: drawReactive
   79: origRenderFunc
   78: output$plot1
    2: shiny::runApp
    1: launch_mchtoolbox [C:/Users/Kyle Hamilton/Documents/GitHub/mchtoolbox/R/launch_mchtoolbox.R#18]`

![screenshotmchtoolbox](https://user-images.githubusercontent.com/2274317/40525303-2f5038b0-5f94-11e8-9a80-7a2338a8e897.png)

**Comment by jenniferthompson** [comment]
@kylehamilton Do you have the viridisLite package installed? We may need to add that to dependencies, I’m not sure (or change the color scales to a non-viridis scale).

I think those scales will be part of the next ggplot2 release; if I’m right about the problem and the release, we could just do a temporary fix and then switch it back, or eventually allow the user to pick their own color scale.

**Comment by kylehamilton** [comment]
I installed the development version of ggplot2 and everything works. I'll just make a note of it when I'm working on it.
